version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/timetable
    volumes:
      - .:/app
      - ./config.yml:/app/config.yml
    depends_on:
      - mongo

  frontend:
    build:
      context: ./static
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
